### ISSUE TITLE
Python 2.7 - UnicodeEncodeError, on model file

### ISSUE THREAD

**Issue by dankon** [figo-connect/python-figo#30]
When user provides wrong credentials for his bank account (tested on Haspa Bank and Warburg Bank) figo API response with message:

> Die Anmeldung zum Online-Zugang Ihrer Bank ist fehlgeschlagen. Bitte überprüfen Sie  Ihre Zugangsdaten.

But this part of [code](https://github.com/figo-connect/python-figo/blob/master/figo/models.py#L664) is raise UnicodeEncodeError for python 2.7:

_Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/home/@@@/env/src/python-figo-master/figo/models.py", line 665, in __str__
    "ended: {self.is_ended}".format(self=self)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 69: ordinal not in range(128)_

**Comment by fricklerhandwerk** [comment]
Sorry for the long delay. PR #32 fixed the issue for this specific call. We're currently focusing on other issues, but this SDK will get more love soon.
